# Generated by Django 2.2.1 on 2019-06-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0002_cocktail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='saved',
            field=models.BooleanField(null=True),
        ),
    ]
