# Generated by Django 2.2.1 on 2019-06-20 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0003_cocktail_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='user',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='saved_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
