# Generated by Django 2.2.1 on 2019-06-20 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0004_auto_20190620_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
