# Generated by Django 2.2.1 on 2019-07-06 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0005_auto_20190620_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
