# Generated by Django 2.2.1 on 2019-07-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0006_cocktail_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
