# Generated by Django 2.2.1 on 2019-07-25 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0007_cocktail_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='cocktail_steps',
        ),
        migrations.CreateModel(
            name='CocktailSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('cocktail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barapp.Cocktail')),
            ],
        ),
    ]
