# Generated by Django 2.2.1 on 2019-07-25 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barapp', '0008_auto_20190724_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(null=True)),
                ('unit', models.CharField(choices=[('PART', 'part'), ('OZ', 'oz'), ('FL OZ', 'fl oz'), ('ML', 'ml'), ('PINCH', 'pinch'), ('WEDGE', 'wedge'), ('DROP', 'drop'), ('SPLASH', 'splash'), ('TBSP', 'tbsp'), ('TSP', 'tsp')], max_length=10)),
                ('cocktail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barapp.Cocktail')),
            ],
        ),
    ]
